[build-system]
requires = ["scikit-build-core[rich,pyproject]"]
build-backend = "scikit_build_core.build"

[project]
name = "pyTransC"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "matplotlib",
    "tqdm",
    "emcee",
    "numdifftools",
    "scikit-learn"
]
